package Swing;

import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class AgregarCommit extends javax.swing.JPanel {
    private examen_labp2.SocialClass amigo;
    public AgregarCommit() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Posts = new javax.swing.JTextArea();
        Perfil = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPost = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(540, 430));
        setPreferredSize(new java.awt.Dimension(540, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 51));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 339, 282, 10));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar Comentario");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 175, 37));

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Buscar: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 29, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("Usuario...");
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 25, 317, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("O--");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 29, 57, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 51));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 75, 299, 10));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        Posts.setEditable(false);
        Posts.setBackground(new java.awt.Color(204, 255, 255));
        Posts.setColumns(20);
        Posts.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Posts.setForeground(new java.awt.Color(0, 0, 0));
        Posts.setRows(5);

        Perfil.setEditable(false);
        Perfil.setBackground(new java.awt.Color(204, 255, 255));
        Perfil.setColumns(20);
        Perfil.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Perfil.setForeground(new java.awt.Color(0, 0, 0));
        Perfil.setRows(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Posts, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Posts, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 91, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setBorder(null);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 120, 115, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Buscar Post: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 116, -1, -1));

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(true);

        txtPost.setBackground(new java.awt.Color(204, 204, 255));
        txtPost.setColumns(20);
        txtPost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPost.setForeground(new java.awt.Color(51, 51, 51));
        txtPost.setRows(5);
        txtPost.setBorder(null);
        txtPost.setOpaque(false);
        jScrollPane1.setViewportView(txtPost);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 191, 253, -1));

        jLabel4.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Post");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 152, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Regresar");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 175, 37));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            LogIn.uber.agregarComment(amigo.getUsername(), 
                jComboBox1.getSelectedIndex(), LogIn.usuario.getUsername(), txtPost.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al comentar.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        // TODO add your handling code here:
        txtUsuario.setText("");
        txtUsuario.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            examen_labp2.SocialClass usuario = LogIn.uber.buscar(txtUsuario.getText());
            amigo = usuario;
            TextPerfil(usuario);
            TextPos(usuario);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ERROR: Ese usuario no existe.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
                Posts.setText(amigo.getPosts().get(jComboBox1.getSelectedIndex()));
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AgregarCommit dd = new AgregarCommit();
        dd.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public void TextPerfil(examen_labp2.SocialClass usuario){
        String tipo = "";
        if(usuario instanceof examen_labp2.Twitter){
            tipo = "Twitter";
        }else{
            tipo = "Facebook";
        }
        Perfil.setText("   Usuario: " + usuario.getUsername());
        try{
            Perfil.setText(Perfil.getText() + "   Amigos: " + usuario.getFriends().size());
        }catch(Exception e){
            Perfil.setText(Perfil.getText() + "   Amigos: " + 0);
        }
        
        try{
            Perfil.setText(Perfil.getText() + "\n   Cuenta: " + tipo + "   Posts: " + usuario.getPosts().size());
        }catch(Exception e){
            Perfil.setText(Perfil.getText() + "\n   Cuenta: " + tipo + "   Posts: " + 0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Perfil;
    private javax.swing.JTextArea Posts;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea txtPost;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void TextPos(examen_labp2.SocialClass usuario) {
        String[] posts=new String[usuario.getPosts().size()];
        for(int ciclo = 0; ciclo< posts.length;ciclo++){
            posts[ciclo] = Integer.toString(ciclo);
        }
        
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(posts));
        Posts.setText(amigo.getPosts().get(0));
                
    }
}