package Swing;
/**
 *
 * @author crist
 */
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
public class LogIn extends javax.swing.JFrame {
    
    public static examen_labp2.SocialClass usuario;
    public static examen_labp2.UberSocial uber = new examen_labp2.UberSocial();
    int XMouse;
    int YMouse;
    
    public LogIn() {
        initComponents();   
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        InicioDeSesion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Registrar1 = new javax.swing.JButton();
        Iniciar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        fondo.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 150, 410));

        InicioDeSesion.setBackground(new java.awt.Color(255, 255, 255));
        InicioDeSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Inicio de Sesión");
        InicioDeSesion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Usuario");
        InicioDeSesion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario1.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario1.setText("Ingrese su Usuario");
        txtUsuario1.setBorder(null);
        txtUsuario1.setOpaque(true);
        txtUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuario1MousePressed(evt);
            }
        });
        InicioDeSesion.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 300, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 102));
        InicioDeSesion.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 280, 10));

        Registrar1.setBackground(new java.awt.Color(0, 0, 204));
        Registrar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Registrar1.setForeground(new java.awt.Color(204, 204, 204));
        Registrar1.setText("Registrarse");
        Registrar1.setBorder(null);
        Registrar1.setBorderPainted(false);
        Registrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registrar1.setFocusPainted(false);
        Registrar1.setFocusable(false);
        Registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar1ActionPerformed(evt);
            }
        });
        InicioDeSesion.add(Registrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 120, 40));

        Iniciar1.setBackground(new java.awt.Color(0, 0, 204));
        Iniciar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Iniciar1.setForeground(new java.awt.Color(204, 204, 204));
        Iniciar1.setText("Iniciar Sesion");
        Iniciar1.setBorder(null);
        Iniciar1.setBorderPainted(false);
        Iniciar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Iniciar1.setFocusPainted(false);
        Iniciar1.setFocusable(false);
        Iniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar1ActionPerformed(evt);
            }
        });
        InicioDeSesion.add(Iniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 120, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("SOCIAL CLASS");
        InicioDeSesion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        fondo.add(InicioDeSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuario1MousePressed
        // TODO add your handling code here:
        if(txtUsuario1.getText().equals("Ingrese su Usuario")){
            txtUsuario1.setText("");
        }
        txtUsuario1.setForeground(java.awt.Color.BLACK);
    }//GEN-LAST:event_txtUsuario1MousePressed

    private void Registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar1ActionPerformed
        // TODO add your handling code here:
        txtUsuario1.setForeground(new java.awt.Color(102,102,102));
        txtUsuario1.setText("Ingrese su Usuario");
        
        Registro registro = new Registro();
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Registrar1ActionPerformed

    private void Iniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar1ActionPerformed
        // TODO add your handling code here:
        usuario = uber.buscar(txtUsuario1.getText());
        if(usuario != null){
            Menu inicio = new Menu();
            inicio.setLocationRelativeTo(this);
            inicio.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "ERROR: No se encuentra ese usuario.");
        }
    }//GEN-LAST:event_Iniciar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws IOException{
       
            uber = new examen_labp2.UberSocial();
           
        new LogIn().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar1;
    private javax.swing.JPanel InicioDeSesion;
    private javax.swing.JPanel Logo;
    private javax.swing.JButton Registrar1;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
